apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: messaging-app
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
      version: green
  template:
    metadata:
      labels:
        app: messaging-app
        version: green
    spec:
      containers:
        - name: messaging-app
          image: nginx:latest
          ports:
            - containerPort: 80

